7 update main page
GSG-FC03/art-gallery2 pull request #9
Opened 2021-06-25 15:41 UTC by FatmaHossam5

7 update main page #8

2021-06-25 19:45 UTC, Adham-93 submitted a review, later dismissed

2021-06-26 08:00 UTC, sara219 requested changes

2021-06-26 08:00 UTC, sara219 commented on css-stlye/style.css
> +    bottom: 30%;
The footer is floating on the page, use : 

```
position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
```

![Screenshot from 2021-06-26 10-57-55](https://user-images.githubusercontent.com/47992412/123506563-735a2900-d66d-11eb-9bd2-e57e4363b9ab.png)

2021-06-26 12:25 UTC, sara219 approved these changes

2021-06-26 12:59 UTC, mo7amedehab97 approved these changes
Well done fatma

2021-06-26 13:03 UTC, EmanHass approved these changes

2021-06-26 13:04 UTC, merged